pages/urls.py
from django.urls import path
from .views import home

app_name = 'pages'

urlpatterns = [
    path('', home, name='homepage'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='todo')),
    path('home/', include('pages.urls', namespace='pages'))
]

todolist/urls.py
from django.urls import path, include
from . import views
    
app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    # path('', views.TodoList.as_view(), name='todo_list'),
    path('<int:id>/', views.todo_detail, name='todo_detail'),
    path('create/', views.create_todo, name='create_todo'),
    path('<int:id>/update/', views.update_todo, name='update_todo'),
    path('<int:id>/delete/', views.delete_todo, name='delete_todo'),
]

pages/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.db import models

class TodoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    class Meta:
        ordering = ('completed','-id')

todolist/forms.py
from django import forms
from .models import TodoItem

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['title', 'description']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.TextInput(attrs={
                'class': 'form-control',
            })
        }

pages/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'pages/home.html')

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoItem
from .forms import TodoItemForm
from .serializers import TodoItemSerializer
from django.http import Http404, JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.db.models import Q
from django.core import serializers
from django.template.loader import render_to_string


# Create your views here.
# class TodoList(APIView):
#     template_name = 'todolist/todo_list.html'

#     def get(self, request, format=None):
#         todos = TodoItem.objects.all()
#         serializer = TodoItemSerializer(todos, many=True)
#         return Response(serializer.data)
    
#     def post(self, request, format=None):
#         serializer = TodoItemSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    


def todo_list(request):
    # todos = TodoItem.objects.all()
    ctx = {}
    search = request.GET.get('q')
    if search:
        todos = TodoItem.objects.filter(Q(title__icontains = search)| Q(description__icontains = search))

    else:
        todos = TodoItem.objects.all()
        
    ctx["todos"] = todos

    if request.is_ajax():
        html = render_to_string(
            template_name="includes/list.html", 
            context={"todos": todos},
            request=request
        )
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    if request.method == 'POST':
        todo = get_object_or_404(TodoItem, id=request.POST['todo_id'])
        todo.completed = not todo.completed
        todo.save()
        return redirect('/')
    return render(request, 'todolist/todo_list.html', context=ctx)


def todo_detail(request, id):
    todo = TodoItem.objects.get(id=id)

    if request.method == 'POST':        
        todo.completed = not todo.completed
        todo.save()
        return redirect(f'/{id}')
    context = {
        'todo': todo,
        }
    return render(request, 'todolist/todo_detail.html', context)


def create_todo(request):
    form = TodoItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('/')
    context = {
        'form': form,
    }
    return render(request, 'todolist/create_todo.html', context)

def update_todo(request, id):
    todo = TodoItem.objects.get(id=id)
    bound_form = TodoItemForm(request.POST or None, instance=todo)
    if bound_form.is_valid():
        bound_form.save()
        return redirect(f'/{id}')
    context = {
        'todo': todo,
        'form': bound_form,
        }
    return render(request, 'todolist/update_todo.html', context)

def delete_todo(request, id):
    todo = TodoItem.objects.get(id=id)
    if request.method == 'POST':
        todo.delete()
        return redirect('/')
    context = {
        'todo': todo
        }
    return render(request, 'todolist/delete_todo.html', context)

pages/templates/pages/home.html
{% extends 'base.html' %}
{% block title %}
    Страницы
{% endblock title %}
{% block content %}
    <h1>Проверка</h1>
{% endblock content %}

todolist/templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
  <title>{% block title %}{% endblock %}</title>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/url-search-params/1.1.0/url-search-params.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  
  <header>
    <div class="container">
      <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">ToDoList</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle dropdown-toggle-split" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Заметки
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url "todo:todo_list" %}">Список</a></li>
                  <li><a class="dropdown-item" href="{% url "todo:create_todo" %}">Создать</a></li>
                  
                </ul>
              </li>
            </ul>
            {% if todos %}
            <i id="search-icon" class="fas fa-search" aria-hidden="true"></i>
            <form class="d-flex" action="." method="GET">
              
              <input class="form-control me-2" type="text"placeholder="Поиск" aria-label="Search" id="user-input">
            </form>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
    
  </header>
  <div class="container mt-3">
    {% block content %}
    {% endblock %}
  </div>
  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>

todolist/templates/includes/list.html
{% if todos %}
    {% for todo in todos %}
    <div class="col bs-callout bs-callout-{% if todo.completed %}success{% else %}danger{% endif %}">
        <div class="row justify-content-between">
            <div class="col-4">
                
                <h4><a href="{{ todo.id }}">{{ todo.title }}</a></h4>
                <p>{{ todo.description|truncatewords:5 }}</p>
                
            </div>
            <div class="col-auto mt-auto mb-auto">
                <form action="." method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="todo_id" value="{{ todo.id }}">
                    <button type="submit" class="btn btn-outline-{% if todo.completed %}success{% else %}danger{% endif %}">{% if todo.completed %}Не выполнил{% else %}Выполнил{% endif %}</button>
                </form>                
            </div>
        </div>        
    </div>
    {% endfor %}
{% endif %}

todolist/templates/todolist/create_todo.html
{% extends 'base.html' %}
{% block title %}Создать{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 col-lg-5">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Создать">
            </form>
        </div>
    </div>
</div>
{% endblock %}

todolist/templates/todolist/delete_todo.html
{% extends 'base.html' %}
{% block title %}Удалить?{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 col-lg-5">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">{{ todo.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Todo status: {% if todo.completed %}Completed{% else %}Not completed{% endif %}</h6>
                    <p class="card-text">{{ todo.description }}</p>
                    <a href="{% url "todo:update_todo" todo.id %}" class="card-link">Обновить</a>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="todo_id" value="{{ todo.id }}">
                        <input type="submit" value="Удалить?">
                    </form>
                </div>
            </div>
            
            
        </div>
    </div>
</div>
{% endblock %}

todolist/templates/todolist/todo_detail.html
{% extends "base.html" %}
{% block title %}{{ todo.title }}{% endblock %}
{% block content %}

  <div class="col bs-callout bs-callout-{% if todo.completed %}success{% else %}danger{% endif %}">
    <div class="row justify-content-between">
      <div class="col-4">
        
        <h4>{{ todo.title }}</h4>
        <p>{{ todo.description}}</p>

        
      </div>
      <div class="col-auto mt-auto mb-auto">
        <form action="." method="POST">
          {% csrf_token %}
          <input type="hidden" name="todo_id" value="{{ todo.id }}">
          <button type="submit" class="btn btn-outline-{% if todo.completed %}success{% else %}danger{% endif %}">{% if todo.completed %}Не выполнил{% else %}Выполнил{% endif %}</button>
        </form><br>
        <a href="{% url 'todo:update_todo' todo.id %}"><button type="button" class="btn btn-outline-primary">Обновить</button></a><br><br>
        
        <a href="{% url 'todo:delete_todo' todo.id %}"><button type="button" class="btn btn-outline-primary">Удалить</button></a>                
      </div>
    </div>        
  </div>

{% endblock %}

todolist/templates/todolist/todo_list.html
{% extends 'base.html' %}
{% block title %}Список дел{% endblock %}
{% block content %}




<h1>Список дел</h1>
<div id="replaceable-content">
{% include 'includes/list.html' %}
</div>


{% endblock %}

todolist/templates/todolist/update_todo.html
{% extends 'base.html' %}
{% block title %}Обновить{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 col-lg-5">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Обновить">
            </form>
        </div>
    </div>
</div>
{% endblock %}